### ISSUE TITLE
麻烦请问该从哪里获取 OpenCL 的 SDK 啊

### ISSUE THREAD

**Issue by liguobing** [TianZerL/Anime4KCPP_Android#1]
在 CMakeLists.txt 中需要设置 OpenCL 和 OpenCV 的 SDK 
OpenCV for Android 可以在这里找到 https://opencv.org/releases/
但 OpenCL 似乎没有 Android 平台的 SDK（抑或是我没找对方法？）
还是说 OpenCL 需要自己编译？？
没有做过图形相关的开发工作，对 OpenCL/CV 属实是不了解
想要重新编译一下 Anime4KCPP_Android，让其可以在手机上使用
麻烦您拨冗指导，感谢感谢

**Comment by TianZerL** [comment]
OpenCL可以用高通的，比较容易获得，理论上用高通的lib编译出来的其他芯片也可以用的。你用其它芯片厂商给的的也行。
一般来说去芯片厂商的网站下sdk就有了。

**Comment by CodeCaiSL** [comment]
同问，能提供下opencl的下载地址吗

**Comment by TianZerL** [comment]
@CoderCaiSL 
安卓需要自己从高通手机里扒出来libOpenCL.so文件来link，再配合[头文件](https://github.com/KhronosGroup/OpenCL-Headers)。

**Comment by CoderCaiSL** [comment]
> @CoderCaiSL 安卓需要自己从高通手机里扒出来libOpenCL.so文件来link，再配合[头文件](https://github.com/KhronosGroup/OpenCL-Headers)。

你好，作者，请教下，demo能直接应用在实时出图吗？能提供下可以直接编译的源码吗？有偿

**Comment by CodeCaiSL** [comment]
> @CoderCaiSL 安卓需要自己从高通手机里扒出来libOpenCL.so文件来link，再配合[头文件](https://github.com/KhronosGroup/OpenCL-Headers)。

@TianZerL 你好，作者，请教下，demo能直接应用在实时出图吗？能提供下可以直接编译的源码吗？有偿
