### ISSUE TITLE
希望提供下本地文件

### ISSUE THREAD

**Issue by CodeCaiSL** [TianZerL/Anime4KCPP_Android#2]
作者你好，我这边一直无法编译，可能是我这边环境配置无法和你的一样，如果可以我希望你能提供下OpenCL/inc的文件，谢谢

**Comment by TianZerL** [comment]
你的问题是什么，找不到符号无法链接？
我当初编译用的libOpenCL.so就是从手头的高通手机里拷贝出来的，现在手机换了，但是应该都是一样的。

**Comment by CoderCaiSL** [comment]
> 你的问题是什么，找不到符号无法链接？ 我当初编译用的libOpenCL.so就是从手头的高通手机里拷贝出来的，现在手机换了，但是应该都是一样的。
libOpenCL.so文件我已经从我手机上拷贝出来了，但是项目里还需要OpenCL/CL文件夹，我不知道这是什么？[OpenCL SDK](https://github.com/KhronosGroup/OpenCL-SDK)的文件夹我不知道是不是我拷贝的文件不对还是如何，一直无法编译

**Comment by CodeCaiSL** [comment]
> 你的问题是什么，找不到符号无法链接？ 我当初编译用的libOpenCL.so就是从手头的高通手机里拷贝出来的，现在手机换了，但是应该都是一样的。

libOpenCL.so文件我已经从我手机上拷贝出来了，但是项目里还需要OpenCL/CL文件夹，我不知道这是什么？[OpenCL SDK](https://github.com/KhronosGroup/OpenCL-SDK)的文件夹我不知道是不是我拷贝的文件不对还是如何，一直无法编译

**Comment by CodeCaiSL** [comment]
> 你的问题是什么，找不到符号无法链接？ 我当初编译用的libOpenCL.so就是从手头的高通手机里拷贝出来的，现在手机换了，但是应该都是一样的。

这个是我出问题的截图
![image](https://github.com/user-attachments/assets/57bc1a20-868c-4569-b0c5-f076d473b0b9)
如果还需要什么信息我补齐，麻烦了

**Comment by CodeCaiSL** [comment]
> 你的问题是什么，找不到符号无法链接？ 我当初编译用的libOpenCL.so就是从手头的高通手机里拷贝出来的，现在手机换了，但是应该都是一样的。

感谢作者回复，我这边已经找到问题了，是因为gradle的版本和jdk版本导致的问题
